### ISSUE TITLE
Error validation-and-storage

### ISSUE THREAD

**Issue by dreddsa5dies** [OWASP/Go-SCP#100]
Hi.
There are code inserts with the bcrypt library in the text [(link).](https://github.com/OWASP/Go-SCP/blob/master/src/authentication-password-management/validation-and-storage.md#storing-password-securely-the-practice) However, the code itself is incorrect.
Here is an example with goplay:
https://play.golang.com/p/kqXCPZ7ifCQ
Suggest the right changes?

**Comment by PauloASilva** [comment]
You mean `CompareHashAndPassword()` arguments in the code sample are in the wrong order, is that it?

I'll be glad to approve your PR to fix this.

Cheers,
Paulo A. Silva

**Comment by dreddsa5dies** [comment]
Please consider and accept the changes

https://github.com/OWASP/Go-SCP/pull/101

**Comment by dreddsa5dies** [comment]
@PauloASilva hi!
https://github.com/OWASP/Go-SCP/pull/101 - changes have been proposed, are there any comments?

**Comment by PauloASilva** [comment]
> @PauloASilva hi! #101 - changes have been proposed, are there any comments?

None other than lack of spare time from my side. Sorry for the delay.

Your changes were released in [v2.6.5](https://github.com/OWASP/Go-SCP/releases/tag/v2.6.5).

**Comment by dreddsa5dies** [comment]
You are best, thanks
