### ISSUE TITLE
Somehow avoid passing nonce to decryption method

### ISSUE THREAD

**Issue by BentCoder** [OWASP/Go-SCP#68]
Hi,

Thanks for this piece of work. The enc/dec example [here](https://github.com/OWASP/Go-SCP/tree/master/src/cryptographic-practices) requires the nonce to be known by both methods. Is there a way to avoid passing to `dec` method? Similar to [this](http://www.inanzzz.com/index.php/post/f3pe/data-encryption-and-decryption-with-a-secret-key-in-golang). See example below - same one from the doc but split into `enc` and `dec` methods.

Thanks

```go
package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

func main() {
	msg := []byte("Hello World!")
	key := []byte("a6df723a921fccda52bdc4ca50851559")

	nonce := make([]byte, 12)
	if _, err := rand.Read(nonce); err != nil {
		panic(err.Error())
	}
	fmt.Println("NONCE:", hex.EncodeToString(nonce))

	enc := enc(msg, key, nonce)
	fmt.Println("ENC:", hex.EncodeToString(enc))

	dec := dec(enc, key, nonce)
	fmt.Println("DEC:", string(dec))
}

func enc(data, key, nonce []byte) []byte {
	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err.Error())
	}

	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		panic(err.Error())
	}

	return aesgcm.Seal(nil, nonce, data, nil)
}

// Somehow this method should avoid requiring `nonce`.
func dec(enc, key, nonce []byte) []byte  {
	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err.Error())
	}

	aesgcm, err := cipher.NewGCM(block)
	if err != nil {
		panic(err.Error())
	}

	decrypted_data, err := aesgcm.Open(nil, nonce, enc, nil)
	if err != nil {
		panic(err.Error())
	}

	return decrypted_data
}
```

**Comment by BentCoder** [comment]
Solution: http://www.inanzzz.com/index.php/post/f3pe/data-encryption-and-decryption-with-a-secret-key-in-golang

**Comment by PauloASilva** [comment]
Hi @BentCoder,
The example you've shared[1] is preferable, since there's a better SoC (Separation of Concerns) between encryption and decryption.

Would you like to open a Pull Request with a refactored source code sample?
I would love to review and accept it!

Cheers,
Paulo A. Silva

[1]: http://www.inanzzz.com/index.php/post/f3pe/data-encryption-and-decryption-with-a-secret-key-in-golang

**Comment by BentCoder** [comment]
Hi @PauloASilva 
I will do and ping you once ready.
Thanks

**Comment by BentCoder** [comment]
Closing this as the update/implementation has been merged here: https://github.com/OWASP/Go-SCP/pull/78
