### ISSUE TITLE
add link to OWASP project page

### ISSUE THREAD

**Issue by jgadsden** [OWASP/Go-SCP#94]
Could we have a link to this OWASP project page for Go-SCP on the right-hand side panel?
Suggest link to https://owasp.org/www-project-go-secure-coding-practices-guide/

**Comment by ErezYalon** [comment]
Done. If this is what you meant:
![image](https://user-images.githubusercontent.com/11692285/217887098-3f6300bd-4ebc-40b7-a00f-193f86d2b28d.png)

**Comment by jgadsden** [comment]
yes, that is perfect, thank you @ErezYalon

**Comment by jgadsden** [comment]
On a related issue, could the pull request #93 be reviewed and merged @ErezYalon or @PauloASilva ?
Many thanks
